apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: notas-k8s
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      run: webapp
  template:
    metadata:
      labels:
        run: webapp
    spec:
      containers:
        - name: webapp
          image: alanlab/notas-k8s
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"