
apiVersion: v1
kind: Service
metadata:
  labels:
    run: webapp
  name: webapp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30022
  selector:
    run: webapp
  type: NodePort
